name: Run Terraform Checks
on:
  pull_request:
permissions:
  id-token: write
  contents: write
jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - uses: nationalarchives/dr2-github-actions/.github/actions/run-git-secrets@main
      - uses: nationalarchives/dr2-github-actions/.github/actions/slack-send@main
        if: failure()
        with:
          message: ":warning: Secrets found in repository dr2-terraform-backend"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
      - name: Configure AWS credentials for S3 state file access
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.MANAGEMENT_ACCOUNT }}:role/MgmtDPBootstrapTerraformGitHubRepositoriesRole
          aws-region: eu-west-2
          role-session-name: TerraformRole
      - name: Terraform Format
        id: fmt
        run: |
          terraform init
          terraform fmt -check --recursive
          terraform validate
