name: Run Terraform Checks
on:
  pull_request:
permissions:
  id-token: write
  contents: write
jobs:
  terraform-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ff7abcd0c3c05ccf6adc123a8cd1fd4fb30fb493
        with:
          submodules: recursive
          token: ${{ secrets.WORKFLOW_TOKEN }}
      - uses: hashicorp/setup-terraform@08cace20605885b578dc4e35c4de153cac368cf3
      - uses: nationalarchives/dr2-github-actions/.github/actions/run-git-secrets@917201e254f112ff041b952dae76ef767cae7378
      - uses: nationalarchives/dr2-github-actions/.github/actions/slack-send@917201e254f112ff041b952dae76ef767cae7378
        if: failure()
        with:
          message: ":warning: Secrets found in repository dr2-terraform-backend"
          slack-url: ${{ secrets.SLACK_WEBHOOK }}
      - name: Configure AWS credentials for S3 state file access
        uses: aws-actions/configure-aws-credentials@c5a43c32e1873343614c533eb83ffabbe5bc53bc
        with:
          role-to-assume: arn:aws:iam::${{ secrets.MANAGEMENT_ACCOUNT }}:role/MgmtDPBootstrapTerraformGitHubRepositoriesRole
          aws-region: eu-west-2
          role-session-name: TerraformRole
      - name: Terraform Format
        id: fmt
        run: |
          terraform init
          terraform fmt -check --recursive
          terraform validate
